name: copilot-deploy-environment

on:
  workflow_dispatch:
  push:
    branches: ["copilot-ci-cd"]
    paths:
      - "samples/apps/copilot-chat-app/**"
      - ".github/workflows/copilot-deploy*"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/copilot-build.yml

  deploy-infra:
    needs: build
    uses: ./.github/workflows/copilot-deploy-infra.yml
    with:
      ENVIRONMENT: int
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}

  deploy-backend:
    needs: [build, deploy-infra]
    uses: ./.github/workflows/copilot-deploy-backend.yml
    with:
      ARTIFACT_NAME: ${{needs.build.outputs.artifact}}
      ENVIRONMENT: int
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}

  deploy-frontend:
    needs: [deploy-infra]
    uses: ./.github/workflows/copilot-deploy-frontend.yml
    with:
      ENVIRONMENT: int
    secrets:
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
